steps:
  # Install dependencies
  - name: python:3.10.13
    entrypoint: pip
    args: ["install", "-r", "src/api/requirements.txt", "-t", "/workspace/src/api"]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'fantasy-golf-staging'
    - '--source'
    - 'src/api'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'GOOGLE_ENTRYPOINT=gunicorn --bind :$PORT --workers 1 --threads 8 run:app'

options:
  logging: CLOUD_LOGGING_ONLY 